# Update the paths
model:
  path: pretrained_models/UniSS


# Changing the infer parameters may reduce performance. 
# Lower temperature and higher repetition_penalty may fix the wierd output audio.
infer_param:
  temperature: 0.7
  top_p: 0.8
  repetition_penalty: 1.1